apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
      env: demo
  template:
    metadata:
      labels:
        app: web-app
        env: demo
    spec:
      containers:
      - name: web-app
        image: ghcr.io/roberthstrand/demo-golang-webapp:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"